package com.abc.trading.events;

public enum EventType {
    SIGNAL,
    ORDER_DENY,
    ORDER_SUBMIT,
    ORDER_ACCEPT,
    ORDER_LIMIT_ACCEPT,
    ORDER_REJECT,
    ORDER_CANCEL,
    ORDER_CANCEL_REJECT,
    ORDER_MODIFY,
    ORDER_MODIFY_REJECT,
    ORDER_EXPIRE,
    ORDER_TRIGGER,
    ORDER_EMULATED,
    ORDER_RELEASED,
    ORDER_FILL,
    POSITION_UPDATE,
    ACCOUNT_STATE
}
