package com.abc.trading.portfolio;

import com.abc.trading.execution.OrderFill;

/** Published for each fill generated by an internal liquidation order. */
public record LiquidationFill(OrderFill fill) {
    public LiquidationFill {
        if (fill == null) throw new IllegalArgumentException("fill is required");
    }
}
